DROP TABLE IF EXISTS user_behavior;
DROP TABLE IF EXISTS travel_diary;
DROP TABLE IF EXISTS spot_road_edge;
DROP TABLE IF EXISTS spot_facility;
DROP TABLE IF EXISTS spot_building;
DROP TABLE IF EXISTS spot_food;
DROP TABLE IF EXISTS spot_place;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  interests VARCHAR(500),
  favorite_categories VARCHAR(500),
  avatar VARCHAR(500),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE spot_place (
  id VARCHAR(32) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL,
  keywords VARCHAR(1000),
  features VARCHAR(1000),
  rating DECIMAL(3,1) DEFAULT 0.0,
  rating_count INT NOT NULL DEFAULT 0,
  click_count INT NOT NULL DEFAULT 0,
  lat DECIMAL(10,7),
  lng DECIMAL(10,7),
  address VARCHAR(255),
  open_time VARCHAR(200),
  image VARCHAR(500),
  description CLOB,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE spot_food (
  id VARCHAR(32) NOT NULL,
  name VARCHAR(100) NOT NULL,
  place_id VARCHAR(32) NOT NULL,
  cuisine VARCHAR(30),
  popularity INT NOT NULL DEFAULT 0,
  description VARCHAR(500),
  price VARCHAR(30),
  location VARCHAR(200),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE spot_building (
  id VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(30),
  place_id VARCHAR(32) NOT NULL,
  lat DECIMAL(11,7),
  lng DECIMAL(11,7),
  description VARCHAR(500),
  rating DECIMAL(3,1) DEFAULT 0.0,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE spot_facility (
  id VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(30) NOT NULL,
  place_id VARCHAR(32) NOT NULL,
  lat DECIMAL(11,7),
  lng DECIMAL(11,7),
  description VARCHAR(500),
  rating DECIMAL(3,1) DEFAULT 0.0,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE spot_road_edge (
  id VARCHAR(50) NOT NULL,
  from_node VARCHAR(50) NOT NULL,
  to_node VARCHAR(50) NOT NULL,
  distance DECIMAL(10,2) NOT NULL,
  ideal_speed DECIMAL(5,1) DEFAULT 4.0,
  congestion_rate DECIMAL(3,2) DEFAULT 1.0,
  allowed_vehicles VARCHAR(255),
  road_type VARCHAR(30),
  place_id VARCHAR(32),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE travel_diary (
  id VARCHAR(32) NOT NULL,
  title VARCHAR(200) NOT NULL,
  content CLOB,
  place_id VARCHAR(32),
  author_id BIGINT NOT NULL,
  click_count INT NOT NULL DEFAULT 0,
  rating DECIMAL(3,1) DEFAULT 0.0,
  rating_count INT NOT NULL DEFAULT 0,
  images VARCHAR(1000),
  videos VARCHAR(1000),
  tags VARCHAR(1000),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE user_behavior (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  target_id VARCHAR(32) NOT NULL,
  behavior_type VARCHAR(20) NOT NULL,
  score DECIMAL(3,1) DEFAULT 1.0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_target_type UNIQUE (user_id, target_id, behavior_type)
);
